name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build, Lint, Type Check, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Set consistent locale and timezone
        run: |
          export TZ=Australia/Adelaide 
          export LANG=en_AU.UTF-8
          export LC_ALL=en_AU.UTF-8

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Run tests
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"
        run: npm run test

      - name: Build project
        run: npm run build
